version: 3.8

services:
  minecraft: 
    image: ghcr.io/enzbdn/mcservermap:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - VERSION=
      - MAPURL=
      - PVP=